name: docs

on:
  push:
    branches: [ master ]

jobs:
  api-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up the Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build docs with Maven
        run: mvn javadoc:javadoc

      - name: Copy to Documentation Website Location
        run: |
          rm -rf docs
          cp -rf target/site/apidocs/. docs


      - name: Commit documentation changes
        run: |
          if [[ git status --porcelain ]]; then
            git config --global user.name 'SebastianGrabowski'
            git config --global user.email 's.gr4bowsk1@gmail.com'
            git add -A
            git commit -m "Automated API website updates."
            git push
          fi